apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: "{{ .Values.agent.name | default "snow-agent" }}-app"
  name: {{ .Values.agent.clusterRoleBinding.name | default "snow-clusterrolebinding"}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.agent.clusterRole.name | default "snow-clusterrole"}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.agent.accountName | default "snow-account" }}
    namespace: {{ .Release.Namespace }}
