kind: Service
apiVersion: v1
metadata:
  labels:
    app: "{{ .Values.aggregator.name | default "snow-aggregator" }}-app"
  name: {{ .Values.service.name | default "snow-service" }}
spec:
  selector:
    app: "{{ .Values.aggregator.name | default "snow-aggregator" }}-app"
  ports:
    - port: 4150
      targetPort: 4150